<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="1" hostname="Agam-PC" failures="1" tests="1" name="Default test(failed)" time="0.063" errors="0" timestamp="2023-01-17T23:50:02 IST">
  <testcase classname="Practise.ListenersPractise" name="methodOne" time="0.015">
    <failure type="java.lang.Exception" message="this is exception !!">
      <![CDATA[java.lang.Exception: this is exception !!
at Practise.ListenersPractise.methodOne(ListenersPractise.java:16)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 25 stack frames]]>
    </failure>
  </testcase> <!-- methodOne -->
  <testcase classname="Practise.ListenersPractise" name="methodtwo" time="0.0">
    <ignored/>
  </testcase> <!-- methodtwo -->
</testsuite> <!-- Default test(failed) -->
